config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'
  get  'topics'     => 'topics#index'
  post 'topics'     => 'topics#create'
  get  'topics/:id/comments' => 'comments#index', as: :comments
  post 'topics/:id/comments' => 'comments#create', as: :create_comment
  post 'topics/:id/comments/:comment_id/reply' => 'comments#reply', as: :reply_comment

end

app/models/comment.rb
class Comment

  include Mongoid::Document
  include Mongoid::Timestamps

  field :text, type: String

  belongs_to :topic
  belongs_to :comment
  has_many   :comments

  validates   :text, presence: true
  before_save :sanitize_text

  protected

  def sanitize_text
    @@blacklist_filter.sanitize(text)
  end

end

app/models/topic.rb
class Topic

  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String

  has_many :comments

  validates :title, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :topic
  respond_to :html

  def index
    @comment  = Comment.new
    @comments = @topic.comments.page(params[:page])
  end

  def create

    @comment = Comment.new(params[:comment].permit(:text))

    if @topic.comments.push(@comment)
      flash[:notice] = t(:comment_created)
      redirect_to(comments_url(@topic))
    else
      flash[:error] =  @topic.errors.full_messages
      render :index
    end

  end

  def reply

    @comment = Comment.find(params[:comment_id])
    @reply   = Comment.new(params[:comment].permit(:text))

    if @comment.comments.push(@reply)
      flash[:notice] = t(:comment_created)
      redirect_to(comments_url(@topic))
    else
      flash[:error] =  @reply.errors.full_messages
      render :index
    end


  end

  private

  def topic
    @topic = Topic.find(params[:id])
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  respond_to :html

  def index
    topics_per_page
    @topic  = Topic.new
  end

  def create

    @topic = Topic.new(params[:topic].permit(:title))

    if @topic.save
      flash[:notice] = t(:topic_created) if @topic.save
      respond_with(@topic, location: root_path)
    else
      flash[:error] =  @topic.errors.full_messages
      topics_per_page
      render :index
    end

  end

  private

  def topics_per_page
    @topics = Topic.all.page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def render_tree(topic, comment, html='')

    html << "<li>#{comment.text}</li><a href='#' class='toggle_reply'>Reply</a>"
    html << form_for_comment_reply(topic, comment)

    comment.comments.each do |c|
      html << "<ul>"
      render_tree(topic, c, html)
      html << "</ul>"
    end

    html.html_safe

  end

  def form_for_comment_reply(topic, comment)

    route = Rails.application
                 .routes
                 .url_helpers
                 .reply_comment_path(topic._id, comment._id)

    form_for(Comment.new, url: route, html: {class: 'form_reply'}) do |f|
      concat(f.text_area :text)
      concat(f.submit 'Salvar')
    end

  end


end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<strong><%= @topic.title %></strong>

<br/>

<%= form_for @comment, url: create_comment_path  do |fc| %>
  <%= fc.text_area :text %>
  <%= fc.submit 'Salvar' %>
<% end %>


<% unless @comments.any?%>
  <p> Nenhum comentário cadastrado </p>
<% end %>

<%= content_tag(:ul) do %>
  <% @comments.each do |comment| %>
    <%= render_tree(@topic, comment) %>
  <% end %>
<% end %>

<%= paginate @comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum R7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <%= link_to '[home]', topics_path %>

  <ul>
    <% flash.each do |k,v| %>
      <li> <%= v %></li>
    <% end %>
  </ul>

  <%= yield %>

</body>
</html>

app/views/topics/index.html.erb
<%= form_for @topic, url: topics_path do |f| %>

  <%= f.text_area :title %>
  <%= f.submit 'Salvar' %>

<% end %>

<% @topics.each_with_index do |topic, idx| %>
  <p> <%= link_to idx, comments_path(topic._id) %> | <%= link_to topic.created_at, comments_path(topic._id) %> | <%= topic.title %></p>
<% end %>

<%= paginate @topics %>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>